"""create movies table

Revision ID: 52391da57c60
Revises: 61335a8297fb
Create Date: 2025-03-12 18:59:43.009625

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "52391da57c60"
down_revision: Union[str, None] = "61335a8297fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie", "vod", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("movie", "vod", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
